[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "subcurrency"

[dependencies]
std = { git = "https://github.com/fuellabs/sway", branch = "feat/transaction-policies" }